name: JSpecify JDK CI tests

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build_jdk:
    name: Build the JDK
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      JAVA_VERSION: 23
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: 23
        distribution: 'temurin'
    - name: Install jtreg
      run: |
        wget https://builds.shipilev.net/jtreg/jtreg-7.5%2B1.zip -O /tmp/jtreg.zip
        unzip /tmp/jtreg.zip -d /tmp/
    - name: Configure the JDK
      run: bash ./configure --with-jtreg=/tmp/jtreg --disable-warnings-as-errors
    - name: Build the JDK
      run: make jdk

