name: JSpecify JDK CI tests

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build_jdk:
    name: Build the JSpecify JDK
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      JAVA_VERSION: 24
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: 24
        distribution: 'temurin'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --only-upgrade apt
        sudo apt-get install gcc-10 g++-10 libcups2-dev libasound2-dev libfontconfig1-dev \
            libx11-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev libxt-dev
    - name: Install jtreg
      run: |
        wget https://builds.shipilev.net/jtreg/jtreg-8%2B2.zip -O /tmp/jtreg.zip
        unzip /tmp/jtreg.zip -d /tmp/
    - name: Configure the JDK
      run: bash ./configure --with-jtreg=/tmp/jtreg --disable-warnings-as-errors
    - name: Build the JDK
      run: make jdk

